import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
const ROOT = fileURLToPath(new URL('..', import.meta.url));
const DIST = join(ROOT, 'dist');
const MIME = { '.html':'text/html', '.js':'text/javascript', '.css':'text/css', '.map':'application/json' };
const server = createServer(async (req,res)=>{ try { const p=decodeURIComponent((req.url??'/').split('?')[0]); const rel=p==='/'?'index.html':normalize(p).replace(/^[/\\]+/,''); res.writeHead(200,{'content-type':MIME[extname(rel)]??'application/octet-stream'}).end(await readFile(join(DIST,rel))); } catch { res.writeHead(404).end(); } });
const port = await new Promise(r=>server.listen(0,'127.0.0.1',()=>r(server.address().port)));
const browser = await chromium.launch({ headless:true, args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage'] });
const page = await browser.newPage({ viewport:{width:800,height:600} });
page.on('pageerror',(e)=>console.log('PAGE ERROR:',String(e)));
await page.goto(`http://127.0.0.1:${port}/`,{waitUntil:'load'});
await page.waitForFunction(()=>!!window.__voxelquest,null,{timeout:20000});
await page.click('#play');
await page.waitForTimeout(6000);
const stats = await page.evaluate(()=>window.__voxelquest.debugAtlasStats());
for (const [name, s] of Object.entries(stats)) console.log(`${name.padEnd(12)} mean ${String(s.mean).padEnd(6)} stdev ${s.stdev}`);
await browser.close(); server.close();
